[package]
name = "orbtk"
description = "The Orbital Widget Toolkit"
repository = "https://github.com/redox-os/orbtk"
version = "0.0.2"
license-file = "LICENSE"
readme = "README.md"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]

[lib]
name = "orbtk"
path = "src/lib.rs"

[[bin]]
name = "example"
path = "src/example.rs"

[dependencies]
sdl2 = "0.9"
sdl2_ttf = "0.9"
